import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://staging.physicswallah.live/');
  await page.getByRole('button', { name: 'Login/Register' }).click();
  await page.getByRole('textbox', { name: 'E.g' }).click();
  await page.getByRole('textbox', { name: 'E.g' }).fill('9012137707');
  await page.getByRole('button', { name: 'Request OTP' }).click();
  await page.locator('#pw_auth-otp_input_0').fill('1');
  await page.locator('#pw_auth-otp_input_1').fill('2');
  await page.locator('#pw_auth-otp_input_2').fill('3');
  await page.locator('#pw_auth-otp_input_3').fill('4');
  await page.locator('#pw_auth-otp_input_4').fill('5');
  await page.locator('#pw_auth-otp_input_5').fill('6');
  await page.getByRole('button', { name: 'Hi, I am your Personal AI' }).first().click();
  await page.getByRole('button', { name: 'Contact Us Contact Us' }).click();
  await page.getByRole('button', { name: 'Contact Us', exact: true }).click();
  await page.getByText('I want to make a request (e.g').click();
  await page.getByText('Batch Change', { exact: true }).click();
  await page.getByText('Raise Ticket').click();
  await page.locator('form svg').click();
  await page.locator('body').setInputFiles('package.json');
  await page.getByText('Please attach the valid').click();
  await page.locator('body').setInputFiles('FILE_IMAGE_2_JPG.jpg');
  await page.locator('textarea[name="comment"]').click();
  await page.locator('textarea[name="comment"]').fill('Test Ticket Ritvik');
  await page.locator('textarea[name="comment"]').press('ControlOrMeta+a');
  await page.locator('textarea[name="comment"]').press('ControlOrMeta+c');
  await page.locator('textarea[name="comment"]').press('ArrowRight');
  await page.locator('textarea[name="comment"]').fill('Test Ticket RitvikTest Ticket RitvikTest Ticket RitvikTest Ticket RitvikTest Ticket RitvikTest Ticket RitvikTest Ticket RitvikTest Ticket RitvikTest Ticket RitvikTest Ticket RitvikTest Ticket RitvikTest Ticket RitvikTest Ticket ');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.locator('svg').nth(4).click();
  await page.getByRole('button', { name: 'Contact Us', exact: true }).click();
  await page.getByText('I want to make a request (e.g').click();
  await page.getByText('Number Change', { exact: true }).click();
  await page.getByText('Raise Ticket', { exact: true }).click();
  await page.getByRole('spinbutton').click();
  await page.getByRole('spinbutton').fill('1234567890');
  await page.locator('div').filter({ hasText: /^Please attach valid invoice details\*$/ }).nth(1).click();
  await page.locator('body').setInputFiles('FILE_IMAGE_2_JPG.jpg');
  await page.locator('textarea[name="comment"]').click();
  await page.locator('textarea[name="comment"]').fill('Test Ticket Ritvik');
  await page.locator('textarea[name="comment"]').press('ControlOrMeta+a');
  await page.locator('textarea[name="comment"]').press('ControlOrMeta+c');
  await page.locator('textarea[name="comment"]').press('ArrowRight');
  await page.locator('textarea[name="comment"]').fill('Test Ticket RitvikTest Ticket RitvikTest Ticket RitvikTest Ticket RitvikTest Ticket RitvikTest Ticket Ritvik');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Track Issue' }).click();
  await page.getByRole('button', { name: 'Study Study' }).click();
});